# Generated by Django 4.0.2 on 2022-02-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recording', '0002_records_vtt'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='Json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
