# Generated by Django 4.0.2 on 2022-02-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recording', '0005_stats_qestion_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats_qestion',
            name='Answer',
        ),
    ]
